### ISSUE TITLE
eda.py

### ISSUE THREAD

**Issue by Fangjj0621** [zhaominyiz/EPiDA#4]
eda.py文件里 from eda import eda,epdi
后面的第三个Translator不是eda里面的吧，这里是不是写错了
是from translator import Translator

**Comment by zhaominyiz** [comment]
eda的代码在nlp_aug里，这里的eda.py实际上混了些translator，eda的变种等code。

**Comment by Fangjj0621** [comment]
ok

**Comment by CaptainAAA** [comment]
> eda的代码在nlp_aug里，这里的eda.py实际上混了些translator，eda的变种等code。

不好意思，我也遇到这个问题，但是我没有看懂回答，可不可以详细解释一下呀？具体要在哪里去找translator呢
