### ISSUE TITLE
关于文档中数据集链接打不开的问题

### ISSUE THREAD

**Issue by CaptainAAA** [zhaominyiz/EPiDA#5]
README文档中的这个链接打不开，https://home.ttic.edu/~freda/paper/shi2021substructure.pdf

请问我应该从哪里获取呢

**Comment by zhaominyiz** [comment]
那要不去看谷歌学术的版本吧

**Comment by CaptainAAA** [comment]
> 那要不去看谷歌学术的版本吧
你好，我不大明白，我是具体要在谷歌学术怎么搜索呢？

**Comment by zhaominyiz** [comment]
Take this!
https://github.com/ExplorerFreda/sub2-augmentation
